Metrics/LineLength:
  Max: 120

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# Metrics/AbcSize:
#   Enabled: false

# Metrics/BlockLength:
#   Enabled: false

Metrics/ClassLength:
  Enabled: false

# Metrics/CyclomaticComplexity:
#   Enabled: false

# Metrics/MethodLength:
#   Enabled: false

# Metrics/PerceivedComplexity:
#   Enabled: false
